// Aquí van los 15 platillos
export const PLATILLOS = [
 { id: "1", nombre: "Pupusas", descripcion: "Tortillas rellenas tradicionales salvadoreñas.", foto: "https://cdn0.recetasgratis.net/es/posts/7/6/4/pupusas_de_chicharron_22467_orig.jpg", ingredientes: ["Harina de maíz", "Queso", "Frijoles", "Chicharrón"], region: "El Salvador", precio: 1.5, categoria: "Principal" },
  { id: "2", nombre: "Tamales", descripcion: "Masa cocida envuelta en hojas, rellena con carne.", foto: "https://prensadehouston.com/wp-content/uploads/2023/08/RECETA-PRINCIPAL-6.jpg", ingredientes: ["Masa", "Hojas de plátano", "Pollo", "Achiote"], region: "Mesoamérica", precio: 2.0, categoria: "Complemento" },
  { id: "3", nombre: "Yuca frita con chicharrón", descripcion: "Yuca frita acompañada de chicharrón y curtido.", foto: "https://i.ytimg.com/vi/a8bhUWQ5lM8/maxresdefault.jpg", ingredientes: ["Yuca", "Aceite", "Chicharrón", "Curtido"], region: "Centroamérica", precio: 3.5, categoria: "Principal" },
  { id: "4", nombre: "Sopa de Pata", descripcion: "Sopa hecha con pata de res y verduras.", foto: "https://swiftmeats.com/wp-content/uploads/2024/06/Swift-Beef-Sopa-de-Pata-640x640-1.jpg", ingredientes: ["Pata de res", "Yuca", "Elote", "Verduras"], region: "El Salvador", precio: 4.0, categoria: "Sopa" },
  { id: "5", nombre: "Baleadas", descripcion: "Tortilla de harina con frijoles, queso y crema.", foto: "https://hl-grocery-prod-master.imgix.net/imgix/recipes/0861911088a0049fd8f7979b7f65dd98faceca6e", ingredientes: ["Harina", "Frijoles", "Queso", "Crema"], region: "Honduras", precio: 2.5, categoria: "Principal" },
  { id: "6", nombre: "Enchiladas Salvadoreñas", descripcion: "Tortilla frita con pollo, vegetales y queso.", foto: "https://www.foodtechlife.com/wp-content/uploads/2025/03/mexican-tostadas-salvadoran-enchiladas.webp", ingredientes: ["Tortilla", "Pollo", "Repollo", "Queso"], region: "El Salvador", precio: 2.0, categoria: "Aperitivo" },
  { id: "7", nombre: "Ceviche", descripcion: "Pescado marinado en jugo de limón con vegetales.", foto: "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_1:1/k%2FPhoto%2FRecipes%2F2019-06-Easy-Shrimp-Ceviche-with-Avocado%2FEasy-Shrimp-Ceviche-with-Avocado_010_a68f7c_cropped", ingredientes: ["Pescado", "Limón", "Cebolla", "Cilantro"], region: "Perú", precio: 6.0, categoria: "Mariscos" },
  { id: "8", nombre: "Arepas", descripcion: "Tortillas de maíz rellenas con diversos ingredientes.", foto: "https://foodinstitute.com/wp-content/uploads/2024/06/Arepa.jpg.webp", ingredientes: ["Harina de maíz", "Queso", "Jamón"], region: "Venezuela/Colombia", precio: 3.0, categoria: "Principal" },
  { id: "9", nombre: "Gallo Pinto", descripcion: "Arroz y frijoles mezclados con especias.", foto: "https://mojo.generalmills.com/api/public/content/9OWfC6hFEkW5MmG3jTPP5w_gmi_hi_res_jpeg.jpeg?v=9cc54784&t=16e3ce250f244648bef28c5949fb99ff", ingredientes: ["Arroz", "Frijoles", "Cebolla", "Cilantro"], region: "Costa Rica/Nicaragua", precio: 2.5, categoria: "Desayuno" },
  { id: "10", nombre: "Carne Asada", descripcion: "Carne de res a la parrilla con guarniciones.", foto: "https://mojo.generalmills.com/api/public/content/KIVwKMkmX0mcxyYnGcQSyA_gmi_hi_res_jpeg.jpeg?v=25af9e9b&t=16e3ce250f244648bef28c5949fb99ff", ingredientes: ["Carne de res", "Especias", "Tortillas"], region: "Latinoamérica", precio: 8.0, categoria: "Principal" },
  { id: "11", nombre: "Chiles en Nogada", descripcion: "Chile poblano relleno cubierto con salsa de nuez.", foto: "https://www.daisybrand.com/wp-content/uploads/2019/12/CHILI-RELLENOS-770x628.jpg", ingredientes: ["Chile poblano", "Carne", "Nuez", "Granada"], region: "México", precio: 10.0, categoria: "Festivo" },
  { id: "12", nombre: "Paella", descripcion: "Arroz con mariscos, pollo y azafrán.", foto: "https://static01.nyt.com/images/2023/10/24/multimedia/MB-Paella-Master-Recipe-vwjm/MB-Paella-Master-Recipe-vwjm-threeByTwoLargeAt2X.jpg", ingredientes: ["Arroz", "Mariscos", "Azafrán"], region: "España", precio: 12.0, categoria: "Principal" },
  { id: "13", nombre: "Feijoada", descripcion: "Guiso de frijoles negros con carne.", foto: "https://recetasdecocina.elmundo.es/wp-content/uploads/2025/01/feijoada-1024x683.jpg", ingredientes: ["Frijoles negros", "Carne de cerdo", "Arroz"], region: "Brasil", precio: 9.0, categoria: "Principal" },
  { id: "14", nombre: "Lomo Saltado", descripcion: "Salteado de carne con papas fritas y arroz.", foto: "https://media.viajarsimple.com/vp/2025/06/Tradicional-Lomo-Saltado-Fusion-Culinaria-Peruana.jpg", ingredientes: ["Carne", "Papas fritas", "Arroz", "Salsa de soya"], region: "Perú", precio: 7.0, categoria: "Principal" },
  { id: "15", nombre: "Ropa Vieja", descripcion: "Carne desmenuzada con tomate y especias.", foto: "https://www.allrecipes.com/thmb/h3LsTZQ5FKdOgD9gCxrOYJEHrr0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/79301-cuban-ropa-vieja-DDMFS-4x3-0daa8085c6cd4423981002ffae990fb1.jpg", ingredientes: ["Carne de res", "Tomate", "Pimientos", "Cebolla"], region: "Cuba", precio: 8.5, categoria: "Principal" },
];
